files:
  - source: /portal-impl/src/content/Language.properties
    translation: /%original_path%/%file_name%_%two_letters_code%.%file_extension%
    languages_mapping:
      locale_with_underscore:
        zh-TW: zh_TW
        zh-CN: zh_CN
